sudo: false
language: node_js

branches:
  only:
    - master

os:
  - osx

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - '4'
  - '6'

before_script:
  - npm prune

script:
  - npm run test
  - npm run e2e

after_success:
  - npm run release