sudo: false
language: node_js
branches:
  except:
  - "/^*-v[0-9]/"
  only:
  - master
os:
  - osx
  - linux
env:
  - NODE_VERSION="6.3.0"
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm run test
  - npm run e2e
after_success:
  - npm run release
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=latest-stable
  - git tag $GIT_TAG -af -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER - export GIT_TAG2=latest-stable - git tag $GIT_TAG2 -a -m "Generated tag from TravisCI for build latest stable" - git push --quiet https://$GITHUB_API_KEY@github.com/ReactivePixels/slinky $GIT_TAG > /dev/null 2>&1 - git push --quiet https://$GITHUB_API_KEY@github.com/ReactivePixels/slinky $GIT_TAG2 -f > /dev/null 2>&1
  - git push --force https://rpocklin:$GITHUB_API_KEY@github.com/ReactivePixels/slinky $GIT_TAG 2>&1
#after_deploy:
deploy:
  provider: releases
  api_key:
    secure: CL2kPbe9n+Ks4iCQh5wNIpXeOtVytLp/1Z+IYXm3UmzDzEF/1xeu4m9Flz7R1JctaBkFOs27zluOXo0i11h2RWIjezbVrYD6vDSIQsqwBkeXTHUolqBARSuIuXfWvKdz7y4ZInhcAfrupM9LKe6r1yLeLcXyuBJKtOAp7jPgbQ3+gfB1OWVahcpXozo8eaOBLJzG+Hg+vfb3OQNbgz2GCLxVuM9q7Gh9qHFlI9HPMM528bQvp2SAdH3Nj1GVzKDKEoqHLu3QkLzWvpbQsWQ+Bp50R55zDoVgWLXletkDDEUxe2OApL+8BrO0pxxyuE+rh6YAwMSC4faZfbrwXyvYtDID06o481j3qbkgacPbFKRlSKng/IZNaGZjuJBJQoC1+2Y2BbEPURE8iFmVhwO1PdfA6f7gM23te3/8tlzV1yS2Cxy/tHLHI5fsB1ctqCddcUiFbYgaOD+MFrMcULjh8386B10br8U0lJrDalIr+4ljr1IWGOQ3rXX70vJHConhaS6g/TFP8DmjK8v9doxADuihPpZFjsA0m2zwkkF28/hPJE4R9WaFIahiyyZ5WkfnCNftAR2FizR4/QgfbJ5rqH/0Y9CEw0u/DDSgZ29vx0zg4ZbgB0mLjBU8jg8UNt14FHFmQxfoIXFn5BIy7BalPmquRQxRoIFUUWJyBDX/JnE=
  file:
    - dist/mac/Slinky-*.dmg
    - dist/mac/Slinky-*-mac.zip
    - dist/mac/LICENSE
  file_glob: true
  skip_cleanup: true
  on:
#    tags: true
    branch: master
notifications:
  email:
    on_success: never
    on_failure: change
