language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
os:
  - osx
before_script:
  - npm prune
after_success:
  - npm run pack:mac
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
