build: off

os: unstable

platform:
  - x64

branches:
  only:
    - master

skip_tags: true

environment:
  nodejs_version: "6.3.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
#  - npm install npm
  - npm install
  - npm prune

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run e2e
